[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SnooPY"
version = "0.1.0"
description = "A description of your project"
authors = [{ name = "Arthur Lenoble", email = "your-email@example.com" }]
dependencies = []
